### ISSUE TITLE
Count Comments on Tweet

### ISSUE THREAD

**Issue by moreeeze** [Jefferson-Henrique/GetOldTweets-python#201]
Hi everybody,
just found this, it's really awesome! Is there any option to count comments aswell as there already is the option to count retweets? 
Does anybody have a solution for that?
Best
moreeeze

**Comment by rahulha** [comment]
If I am not wrong, by comments you mean replies. I did modify for my own purpose and created an online tool called orgneat

use following line in got -> manager -> TwitterManager.py -> getTweets method

replies = int(tweetPQ("span.ProfileTweet-action--reply span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", "").strip())

This will give you exactly what you want.

**Comment by moreeeze** [comment]
Thanks a lot for your reply! Yes, I mean replies, sorry! Sounds exactly like that could be the solution!
I copied it under permalink,unfortunately, it doesn't work for me, I get the following error:

`File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 4, in <module>
    import got
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/got/__init__.py", line 2, in <module>
    import manager
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/got/manager/__init__.py", line 2, in <module>
    from TweetManager import TweetManager
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/got/manager/TweetManager.py", line 50
    geo = ''
    ^`

Do you know what might be the issue here?
Thanks a lot for your help!

**Comment by rahulha** [comment]
Ohh yes, the code line I gave is for Python 3.5x. That is work in got3 version. Lower versions of Python have different way of removing white spaces in place of strip(). Use this:

replies = int(tweetPQ("span.ProfileTweet-action--reply span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""))

This should fix the error.

**Comment by moreeeze** [comment]
Thanks, but I still get the same issue, any idea what could help?

**Comment by moreeeze** [comment]
Hi, I don't get any error messages, maybe you saw my first comment which I edited. I copy+pasted the line in my editor and this gave me an error, I put it in manually and then it worked. Unfortunately, I don't have any replies in the exported csv, do you know how I can inlude it in the file?

**Comment by rahulha** [comment]
In Exporter.py do you see 
**def receiveBuffer(tweets):**

above and below this function there are lines to write in the file starting with **output.write**
This line of code writes into the CSV file. You need to update these to add any additional fields you like.

Note: The line above def writes header row to file and line below writes the rows.

**Comment by moreeeze** [comment]
Hi, thanks a lot for your help! Unfortunately, I get an error: 
`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/got/manager/TweetManager.py", line 70, in getTweets
    receiveBuffer(resultsAux)
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 66, in receiveBuffer
    outputFile.write(('\n%s;%s;%d;%d;"%s";%s;%s;%s;"%s";%s' % (t.username, t.date.strftime("%Y-%m-%d %H:%M"), t.retweets, t.favorites, t.text, t.geo, t.mentions, t.hashtags, t.id, t.permalink, t.replies)))
AttributeError: Tweet instance has no attribute 'replies'`

What might be the issue here?

**Comment by rahulha** [comment]
The replies variable above in my comment is just a variable that is holding # of replies
You need to assign that to Tweet model that actually is being referred back in Exporter.py

so you need to do:

replies = int(tweetPQ("span.ProfileTweet-action--reply span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""))

tweet.reply = replies  (if you see the code, you'll know where to add this.)

Then try to access replies in Exporter and you should be good.

**Comment by moreeeze** [comment]
Hi,
thanks, tried that, still get an issue:
`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/got/manager/TweetManager.py", line 70, in getTweets
    receiveBuffer(resultsAux)
  File "/Library/Python/2.7/site-packages/GetOldTweets-python-master/Exporter.py", line 66, in receiveBuffer
    outputFile.write(('\n%s;%s;%d;%d;"%s";%s;%s;%s;"%s";%s' % (t.username, t.date.strftime("%Y-%m-%d %H:%M"), t.retweets, t.favorites, t.text, t.geo, t.mentions, t.hashtags, t.id, t.permalink, t.replies)))
AttributeError: Tweet instance has no attribute 'replies'`

Something still seems to be missing to register it in the instance, do you know what might cause this? I really appreciate your help, still a beginner with Python!

**Comment by moreeeze** [comment]
Thanks a lot for your help, working perfectly now!
Awesome tool!
