### ISSUE TITLE
Not able to get tweets data

### ISSUE THREAD

**Issue by giordano91** [Jefferson-Henrique/GetOldTweets-python#60]
Hi Jefferson,
I'm using your code in my Python project which worked well until yesterday. 
This morning I faced in a issue reported by other users too. 
Basically, when I try to run this query
`python Exporter.py --since 2015-02-13 --until 2015-02-19 --querysearch "technology, stock"`
output is always an empty csv file. I tried to debug the problem and I have noticed a couple of points:
the first one is that your code works well if the query regards tweets posted in the last 7 days. 
Is it possible that there is a Twitter restriction here?
About the second one, I hypothesize the problem is in **TweetManager.py** line 21; the length of **json['items_html'] is equals to 0** and so nothing is saved.

Any ideas about it? 

Thank you

Giordano

**Comment by phaerus** [comment]
(I am not Jefferson) but I was able to run that query successfully and got several hundred results before I stopped it. 

`(venv-2.7)[hostname]$ python Exporter.py --since 2015-02-13 --until 2015-02-19 -                                                                                      -querysearch "technology, stock"
Searching...

More 100 saved on file...

More 100 saved on file...

More 100 saved on file...

More 100 saved on file...

Done. Output file generated "output_got.csv".
`
Did you set up a virtual environment for the python?

**Comment by giordano91** [comment]
First of all thank you for the fast feedback. Anyway, you are right, now it's working. 
I don't know why, because I didn't change anything in my environment. 
I'm going to closing this issue.

Thank you!

**Comment by dlkoch06** [comment]
Could either of you help me get this running? Working in Python27 and have downloaded the zip file but still having issues.. Thanks

**Comment by phaerus** [comment]
HI dlkoch06 - 
What do you mean? You have Python 2.7 installed, and you downloaded the zip file from GItHub for GOT? Have you tried just extracting it and running the main.py examples?

**Comment by dlkoch06** [comment]
Apologies, I am a new user. I have attempted to run the main file, but after executing it it returns the exact script in a firefox web browser. It is probably a simple environmental fix, but saw you both had recently had success so I figured I would reach out.

**Comment by phaerus** [comment]
er, are you trying to execute it by pointing a browser to the *.py files? Unless you have something set up to handle the web requests and run the python, it probably won't end well.

best way will be with the Python command line. If you're on windows, download the Python 2.7.9 version and try with that on the command line. The syntax is provided in the readme.md file. If you're on a Linux distro, just install the right Python version (or if on shared hosting, download the tgz and install from source), and then install the needed Python packages, and run with the syntax of "python <or path to specific python version> Exporter.py <flags>"

**Comment by dlkoch06** [comment]
Thank you for the help. I am now getting the "ImportError: No module named models" now. Saw the other message. I downloaded SourceTree and have cloned the package into a new folder within the "C:/Python27" path. Any recommendations from here?

**Comment by phaerus** [comment]
it's wherever you're running you're script from, for the most part. If you have a folder for your project,. just make sure that the GetOldTweets files and folders are in there. so you'd run the python executable, with the parameter of the script and other flags. The error message you're seeing means that wherever/however you're running things, it can't find that models folder and run the init.py script in it

**Comment by dlkoch06** [comment]
I was running the wrong main.py file. I have it now. Thank you for your help/patience.

**Comment by NagaVemprala** [comment]
Sometimes json['items_html'] from TweetManager.py is not pulling the data properly. Eventhough when I copy paste the whole json downloaded from the URL link in http://json.parser.online.fr/ I am able to see all the Tweets data properly rendered. I dont know what is the problem though. Still debugging.

**Comment by NagaVemprala** [comment]
It is resolved for me now. I did not use the headers dictionary while pulling the data. request = urllib.request.Request(url, headers=headers) 
                        response = urllib.request.urlopen(request) 
                        jsonResponse = response.read()

Headers dictionary that I used: 
 headers = {
                        'Host': "twitter.com",
                        'User-Agent': "Mozilla/5.0 (Windows NT 6.1; Win64; x64)",
                        'Accept': "application/json, text/javascript, */*; q=0.01",
                        'Accept-Language': "de,en-US;q=0.7,en;q=0.3",
                        'X-Requested-With': "XMLHttpRequest",
                        'Referer': url,
                        'Connection': "keep-alive"
                }

**Comment by xiaolienahu** [comment]
To NagaVemprala, I am experiencing the same problem. I used your code but it didn't work. Could you share your whole getJsonReponse function here?
